# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 19
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Run tests
      run: npm test
      with:
        env:
          TEST_TOKEN: ${{secrets.TEST_TOKEN}}
          TEST_CHANNEL: ${{secrets.}}
          TEST_CHANNEL_TEXT_OPS: ${{secrets.TEST_CHANNEL}}
          TEST_GUILD: ${{secrets.TEST_GUILD}}
          TEST_USER: ${{secrets.TEST_USER}}
          TEST_MESSAGE: ${{secrets.TEST_MESSAGE}}
